export const CARDS_PLAYER_1 = "CARDS_PLAYER_1"
export const CARDS_PLAYER_2 = "CARDS_PLAYER_2"
export const CARDS_PLAYER_ME = "CARDS_PLAYER_ME"
export const ALL_CARDS = "ALL_CARDS"
export const GAME_POT = "GAME_POT"
export const WHICH_MY_STEP = "WHICH_MY_STEP"